### ISSUE TITLE
NDK version 

### ISSUE THREAD

**Issue by Krakawet** [alecvn/kivy-android-camera#1]
Hi alecvn !

I struggled a bit to get your promising exemple working.
Followed the tutorial, got the error :

>[INFO]:    Available Android APIs are (27, 28)
>[INFO]:    Requested API target 28 is available, continuing.
> [INFO]:    Found NDK version 17c
> [ERROR]:   Build failed: The minimum supported NDK version is 19
> *** The currently recommended NDK version is 19b ***

So I update buildozer.spec in order to use ndk version 19b as recommended by buildozer.

>android.ndk = 19b

Now working, thank you !

**Comment by alecvn** [comment]
Hi @Krakawet, thanks for letting me know.  I believe this has to do with the version of `buildozer` that is running.  On my work machine I need `17c` and at home I need `19b`, and everything else except for the way I installed `buildozer` is the same.  Luckily this error message is quite clear.  Glad you got it working.

**Comment by faziletgokbudak** [comment]
Hi,
I could not find where the image is saved on phone.
Thanks!
