### ISSUE TITLE
Image not saved after captured

### ISSUE THREAD

**Issue by faziletgokbudak** [alecvn/kivy-android-camera#3]
Hi,
I could not find where the image is saved on the phone.
Thanks!

**Comment by alecvn** [comment]
Hi
It should be available in `My Files > Internal Storage > Pictures`.

If it's not there just check the logs and confirm that it is actually successfully saving the file.  You can also add a log to show the path where it will be stored.  It's set in `main.py` line 34:

    storageDir = Context.getExternalFilesDir(Environment.DIRECTORY_PICTURES)

**Comment by faziletgokbudak** [comment]
I think it just saves the image to the internal storage of the app. I am new in Android development. I could not figure out how to save it to an external storage such as inside sdcard.

Any help appreciated a lot!

**Comment by faziletgokbudak** [comment]
I think it saves the image to the internal storage of the app. 
To solve the problem, I changed line 34 with the following:
            storageDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)

Thanks!
