### ISSUE TITLE
File provider issues on Android 10

### ISSUE THREAD

**Issue by Robinosius** [alecvn/kivy-android-camera#4]
File provider has been moved to "androidx.core.content.FileProvider" on Android 10, which breaks the existing API call and raises a Java exception. Intent is still working though.

**Comment by alecvn** [comment]
Thanks!  This "project" was just to kickstart people struggling to get the native Android camera working at the time.  I believe that this has become easier to do in the meanwhile with either Kivy or one of the related libraries.

I will update the documentation to reflect the changes in Android 10.

**Comment by Robinosius** [comment]
Yeah sure, and I really appreciate the effort - I just wanted to let people know that there have been some changes

**Comment by alecvn** [comment]
Much appreciated!

**Comment by tomgold182** [comment]
It is still pretty hard to get the camera API working with kivy/plyer :)

**Comment by alecvn** [comment]
That is truly a shame.  I originally meant to do work on Kivy/Plyer directly but the barrier to entry was a little high for me at the time and I needed to get my project up and running quickly so I did this "dirty" setup.  I'm a little swamped right now but I will try to look into it again in a few weeks.

**Comment by Robinosius** [comment]
Yeah, it's not an easy task.
I actually managed to implement a working camera with an app before, but by creating my own camera screen. But it lead to issues when trying to resize the Image widget. It worked, but didn't look great. So I'd prefer using the native camera application of the devices. It does work (worked around using the FileProvider because I don't really need it), but I've currently got some issues with the conversion of the Bitmap returned by the Intent when calling the compress method. But it should work if I manage to fix that issue. I'll let you know!

**Comment by alecvn** [comment]
Yes, in the final version of my app I think I also removed the `FileProvider` requirement, since I wasn't needing to easily access a photo exactly, but rather wanted to pass the Camera to OpenCV.  So the `FileProvider` requirement is really only necessary if you want to access photos that you've taken from your gallery.  I should probably mention that in the README as well...

**Comment by Robinosius** [comment]
So I managed to make some more things work, but I'm still kind of stuck.
I've been trying to save the images to the user_data_dir to avoid the FileProvider. 
The intent is working, and I'm receiving the image as a Bitmap by binding a callback to onActivityResult. Works fine, and by the size of the bitmap received in the code, it should be the actual image.
However, whenever I try to save the image using the Java FileOutputStream using the usual Java practice, it does save the file to the specified path, but it's empty - 0 bytes.
Using the Bytes as input for a kivy.core.Image has actually worked, but this raised an exception when trying to use the save method "unable to determine size of the pixels". I'll see if I can make things work later.

What did you use in your application? I must admit that I'm not too familiar with Java, but all the pyjnius stuff has been pretty straight forward so far.
